site_name: KotaJá 
site_description: Documentação do projeto KotaJá
site_author: KotaJá
repo_name: KotaJa
repo_url: https://github.com/milenaaires/KotaJa
edit_uri: edit/main/docs/

theme:
  name: material
  language: pt
  logo: assets/logo/fusca.png
  favicon: assets/logo/fusca.png
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - content.code.copy
    - toc.follow
  palette:
    # Tema claro
    - scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/weather-night
        name: Alternar para modo escuro

    # Tema escuro
    - scheme: slate
      primary: orange
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Alternar para modo claro
        
nav:
  - Início: index.md

  - Especificação Funcional:
      - Planning: 00-planning.md
      - Visão e Escopo: 01-visao-escopo.md
      - Papéis e Responsabilidades: 02-papeis-responsabilidades.md
      - Fluxos Funcionais: 03-fluxos-funcionais.md
      - Requisitos: 04-requisitos.md
      - User Cases: 05-user-cases.md
      - User Stories: 06-user-stories.md

  - Modelo de Dados:
      - Modelagem (Entidades): 07-modelagem-entidades.md
      - ERD: 08-erd.md
      - Regras e Índices: 09-regras-integridade-indices.md
      - Dicionário de Dados: 10-dicionario-dados.md
      - Modelo Físico (DDL): 11-modelo-fisico-ddl.md
      - Notas de Modelagem: 12-notas-modelagem.md

  - Arquitetura:
      - Arquitetura Alto Nível: 13-arquitetura-alto-nivel.md
      - Arquitetura de Componentes: 14-componentes.md
      - Estrutura de Pastas: 15-estrutura-pastas.md

  - Technical Design:
      - Fluxo Técnico (Consulta): 16-fluxo-tecnico-consulta.md
      - Contratos (Services/Repos): 17-contratos-servicos-repos.md
      - Estratégia Técnica: 18-estrategia-tecnica.md
      - Decisões de Design: 19-decisoes-design.md
      - Estratégia de Testes: 20-estrategia-testes.md
      - Batch Mensal (Design): 21-batch-design.md

  - UX / Protótipos:
      - Protótipos: 22-prototipos.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - glightbox

extra:
  generator: false

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - javascripts/extra.js



